FROM python:3.9-alpine

ENV PYTHONUNBUFFERED 1

COPY ./requirements.txt /requirements.txt
RUN apk add --update --no-cache postgresql-client build-base
RUN apk add --update --no-cache --virtual .tmp-build-deps \
      gcc libc-dev linux-headers postgresql-dev
RUN apk add libxslt-dev libxml2-dev
RUN pip install -r /requirements.txt
RUN apk del .tmp-build-deps

RUN mkdir /usr/src/api
WORKDIR /usr/src/api
COPY . /usr/src/api


RUN adduser -D user
USER user
